version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    image: pxe-demo:latest
  test:
    image: busybox
    command: 
    - /bin/sh
    - -c
    - "wget http://app:8080"
    depends_on:
    - app